# Generated by Django 5.2.1 on 2025-05-31 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('details', models.TextField(blank=True, verbose_name='Опис')),
                ('type', models.CharField(choices=[('link', 'посилання'), ('file', 'Файл'), ('image', 'зображення'), ('youtube', 'youtube посилання')], max_length=15, verbose_name='Тип матеріала')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Посилання')),
                ('y_link', models.URLField(blank=True, null=True, verbose_name='Посилання ютуб')),
                ('file', models.FileField(blank=True, null=True, upload_to='material/files', verbose_name='Файл')),
                ('image', models.ImageField(blank=True, null=True, upload_to='material/image', verbose_name='Зображення')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлення')),
                ('us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ким додано')),
            ],
        ),
    ]
